name: subumiru2
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: src/assets/fonts/NotoSansJP-Regular.ttf
          weight: 400
        - asset: src/assets/fonts/NotoSansJP-Medium.ttf
          weight: 500
        - asset: src/assets/fonts/NotoSansJP-Bold.ttf
          weight: 700